def lives_given(dificulty):
    """Assings number of lives depending on difficulty"""
    if dificulty == 'easy':
        lives = 10
        return lives
    elif dificulty == 'hard':
        lives = 5
        return lives
 
def check_answer(guessed_number, random_number,lives):
    """Checks the user's answer vesus the random number generated by computer"""
    if guessed_number > random_number:
        lives -= 1
        if lives >0:
            print("Too high.")
            print("Guess again.")
            print(f"You have {lives} attempts remaining to guess the number.")
        else:
            print("You've run out of guesses, you lose.")
            return False
        return lives
    elif guessed_number < random_number:
        lives -= 1
        if lives >0:
            print("Too low.")
            print("Guess again.")
            print(f"You have {lives} attempts remaining to guess the number.")
        else:
            print("You've run out of guesses, you lose.")
            return False
        return lives
    elif guessed_number == random_number: 
        print(f"You  got it right, the answer was {random_number}.")
        return False
     

